# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 325dceb32368643e01fc93a00df70032b1578b4dbf5f637de226677dcfe91fdc7dd687973122615be1c1e0271ffeb8c272f3eaf6d9d858fbaf8496d5964ee3b9

test:
  secret_key_base: 3478326b9c097ece611c4f4bf3bc2b13727bee200ed74e2c114c89ab486381031331e78349931a50dec12f37b528a6bd5653feb2909dd098711fa163b4e9e924

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
